### ISSUE TITLE
TypeError: compilation.updateAsset is not a function

### ISSUE THREAD

**Issue by shenzhongkang** [sorrycc/esbuild-webpack-plugin#13]
I tried to modify `webpack.config.prod.js`and replace option `optimzation` with the example code, and then `npm run build`.
It give me this:
```bash
build [==================  ] 91%TypeError: compilation.updateAsset is not a function
...
at processTicksAndRejections (internal/process/task_queues.js:97:5)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
...
```

**Comment by dream9x** [comment]
I just ran into this issue. Updating to the latest webpack resolved this problem for me.

**Comment by KKKyrie** [comment]
I just ran into the same problem.  
My project is based on vue-cli, @vue/cli-service version is 3.10.0 and it depends on webpack >=4 < 4.29  
  
here's my `vue.config.js`:
```javascript
module.exports = {
  configureWebpack: {
      optimization: {
          minimizer: [
            new ESBuildPlugin({ target: 'es5' })
          ]
      },
  }
}
```  
  
Ask for help 😿
