### ISSUE TITLE
target 默认设置为 es5

### ISSUE THREAD

**Issue by await-ovo** [sorrycc/esbuild-webpack-plugin#19]
### 问题
esbuild 默认 target 是 esnext, 压缩时会引入 es6 语法

![image](https://user-images.githubusercontent.com/41503212/91709585-87e8a480-ebb5-11ea-845c-4090b6afbf3e.png)

### 解决方法
transform 时 默认 target 为 es5

**Comment by BangKk** [comment]
@diem98 这个 plugin 现在好像不支持吧？

**Comment by dionshihk** [comment]
I proposed a Pull Request (https://github.com/sorrycc/esbuild-webpack-plugin/pull/20), to allow passing options to the builder, then you can customize `{target: "es5"}`.

**Comment by sorrycc** [comment]
手动设吧，默认就不设了，未来不是 es5 的。
