### ISSUE TITLE
runtime error  when use webpack 5 with optimization.runtimeChunk after minify

### ISSUE THREAD

**Issue by await-ovo** [sorrycc/esbuild-webpack-plugin#26]
## Reproduction
simple demo use webpack 5 and esbuild-webpack-plugin
* `git clone https://github.com/diem98/webpack5-esbuild-demo.git`
* `git checkout esbuild-0.7`
* `yarn && yarn build && yarn start`
* then open localhost:8080/index.html, you will see the error below:
![image](https://user-images.githubusercontent.com/41503212/105495372-11307d00-5cf7-11eb-9b97-1b30eda2ed03.png)

here is my webpack.config.js: 
```
const ESBuildWebpackPlugin = require('esbuild-webpack-plugin').default;
const HtmlWebpackPlugin = require('html-webpack-plugin');
module.exports = {
  "mode": "production",
  entry: {
    'app': './src/index.js'
  },
  module: {
    rules: [
      {
        test: /\.svg$/,
        use: ['@svgr/webpack', 'url-loader'],
        type: 'javascript/auto'
      }
    ]
  },
  optimization: {
    minimize: true,
    minimizer: [
      new ESBuildWebpackPlugin({})
    ],
    runtimeChunk: {
      name: entrypoint => `runtime~${entrypoint.name}`
    }
  },
  plugins: [
    new HtmlWebpackPlugin({
      filename: 'index.html',
      template: './index.html'
    })
  ]
}
``` 

## System Info
* macos
* node version: v12.20.1
* yarn version: 1.22.5

## Additional context

Upgade esbuild to 0.8 should fix this problem：
repo: `git clone https://github.com/diem98/webpack5-esbuild-demo.git`
branch:` main `

Can we release a version that supports webpack 5 and esbuild0.8

**Comment by peakchen90** [comment]
**webpack 5:**

DeprecationWarning: optimizeChunkAssets is deprecated (use Compilation.hooks.processAssets instead and use one of Compilation.PROCESS_ASSETS_STAGE_* as stage option)
